target-version = "py312"
fix = true
cache-dir = ".ruff_cache"
exclude = [
    ".ruff_cache",
    ".venv",
    "venv",
]
indent-width = 4
line-length = 120
output-format = "grouped"


[lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"

[lint]
mccabe.max-complexity = 6
select = [
    "ALL",
]
ignore = [
    "COM812",
    "FIX002",
    "TD003",
    "TC001",
    "TC002",
    "TC003",
    "D203",
    "D213",
    "D100",
    "D104",
    "D107",
    "N999",
]

[lint.extend-per-file-ignores]
"tests/*" = [
    "ANN001",
    "ANN201",
    "ANN202",
    "D101",
    "D102",
    "D103",
    "S101",
    "PLR0913",
    "S113",
    "SLF001",
    "PT011",
    "ARG001",
    "C901",
    "RUF001",
    "PLR2004",
    "FBT001",
]

[format]
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = 120
indent-style = "space"
quote-style = "single"