"""Create secrets table.

Revision ID: 8c4fad2b4944
Revises:
Create Date: 2026-06-29 19:37:18.520024

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8c4fad2b4944'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'secrets',
        sa.Column('id', sa.Uuid(), nullable=False, comment='Unique secret identifier'),
        sa.Column('secret_text', sa.Text(), nullable=False, comment='Secret text content'),
        sa.Column(
            'created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'
        ),
        sa.Column(
            'update_at',
            sa.DateTime(timezone=True),
            nullable=False,
            comment='Timestamp when the record was last updated',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secrets')
    # ### end Alembic commands ###
